### ISSUE TITLE
[wip] php7.0-fpm experiment in local VM and dynamic nginx hosts config.

### ISSUE THREAD

**Issue by Paulmicha** [guiajlopes/nginx-drupal-dev#1]
I've been trying this setup in an attempt to upgrade a local VM I used for local dev.

This is where I've got, but it's currently broken (502) :
https://github.com/Paulmicha/debian-quickup/blob/master/LEMP%2FUbuntu14.04_Nginx_Php7.script.sh

→ Have you ever tried a dynamic nginx setup like this ?
(perhaps I'm missing something in the FastCGI configuration with the `php7.0-fpm` package, or permissions).

**Comment by guiajlopes** [comment]
You should configure upstream_php.conf based on your PHP-FPM configuration, it's configured to use with this configuration: https://github.com/guiajlopes/php-fpm

Please reopen this issue, if you have more issues. Thanks :)
